[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    ".cache"
  ]

[build]
  publish = "_site"

[[redirects]]
  from = "https://11tybundle.dev/categories/frontmatter/"
  to = "https://11tybundle.dev/categories/front-matter/"
  status = 301

[[redirects]]
  from = "https://11tybundle.dev/archive/"
  to = "https://11tybundle.dev/blog/"
  status = 301

[[redirects]]
  from = "https://11tybundle.dev/posts/*"
  to = "https://11tybundle.dev/blog/:splat"
  status = 301

[[redirects]]
  from = "https://11tybundle.dev/categories-test/"
  to = "https://11tybundle.dev/categories/"
  status = 301

[[redirects]]
  from = "https://11tybundle.dev/categories/11ty-conference/"
  to = "https://11tybundle.dev/categories/11ty-conference-2024/"
  status = 301

[[headers]]
  for = "/feed.xml"
  [headers.values]
    cache-control = "max-age=7200"

[[headers]]
  for = "/firehosefeed.xml"
  [headers.values]
    cache-control = "max-age=7200"
